version: '3.5'

services:
  rabbitmq:
    container_name: test_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_PASS: devuser
      RABBITMQ_DEFAULT_USER: devuser
    logging:
      driver: none
    networks:
      - test-network

  lib:
    container_name: test_lib
    image: node:lts
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - rabbitmq
    command: yarn test
    links:
      - rabbitmq
    networks:
      - test-network
    environment:
      CI: 'true'

networks:
  test-network:
    driver: bridge
