export const RABBITMQ_APPENDER_OPTIONS = Symbol('RABBITMQ_APPENDER_OPTIONS');
export const RABBITMQ_APPENDER_PRODUCER = Symbol('RABBITMQ_APPENDER_PRODUCER');
export const RABBITMQ_REMOTE_LOGGER = Symbol('RABBITMQ_REMOTE_LOGGER');
