name: ci

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Integration Testing Under Docker Compose
        run: docker-compose up -f docker-compose.test.yml --exit-code-from lib
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./reports/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
