name: ci

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies and Build
        run: |
          yarn
          yarn build
      - name: Run Tests With Docker-Compose
        run: docker-compose -f docker-compose.test.yml up  --exit-code-from lib
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./reports/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
